version: '3'
services:

  hours-api:
    build: .
    volumes:
      - ../:/app
      - ~/.m2/:/home/hours/.m2/
    ports:
      - "8000:8000"
    environment:
      - BROKER_HOST=broker:9092

  broker:
    image: spotify/kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      - TOPICS=pending-cmds,succeed-cmds,failed-cmds
